### ISSUE TITLE
Power up Power down sequence missing

### ISSUE THREAD

**Issue by aravindev** [DaxBot/daxc02#1]
Hi,
I was working with the same camera on Jetson TX1 and found that the write to reset the camera chip wasn't going through. I managed to get it working by adding power up/power down sequence using ov5693 code as reference.

I see that you had identified some changes for the compliance test to pass, but the git version seems to miss those changes. Can you share the changes that I should be making to get the compliance test pass.

I am trying to capture an image, got a raw capture using yavta but haven't succeeded in debayering it. Please provide your suggestions if any to debayer image from RG12.

**Comment by wilkinsw** [comment]
What did you add to the power sequence?  I'm enabling the regulators in the order that the MT9M021 wants in daxc02_power_on, which has worked for me so far.  I assume you're using your own custom carrier board.

What is the result of your compliance test?

Using yavta I pass the raw into this:  https://github.com/jdthomas/bayer2rgb

```
yavta /dev/video1 -c1 -n1 -s1280x720 -fSRGGB12 -Fdata.raw
bayer2rgb --input=data.raw --output=data.tiff --width=1280 --height=720 --bpp=16 --first=RGGB --method=BILINEAR --tiff --swap
```

**Comment by YoshuaNava** [comment]
Following on aravindev post, the result of our compliance test is:
```

Driver Info:
	Driver name   : tegra-video
	Card type     : vi-output-0, daxc02 6-0010
	Bus info      : platform:vi:0
	Driver version: 3.10.96
	Capabilities  : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format

Compliance test for device /dev/video0 (not using libv4l2):

Required ioctls:
	test VIDIOC_QUERYCAP: OK

Allow for multiple opens:
	test second video open: OK
	test VIDIOC_QUERYCAP: OK
	test VIDIOC_G/S_PRIORITY: OK

Debug ioctls:
	test VIDIOC_DBG_G/S_REGISTER: OK (Not Supported)
	test VIDIOC_LOG_STATUS: OK (Not Supported)

Input ioctls:
	test VIDIOC_G/S_TUNER/ENUM_FREQ_BANDS: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_S_HW_FREQ_SEEK: OK (Not Supported)
	test VIDIOC_ENUMAUDIO: OK (Not Supported)
	test VIDIOC_G/S/ENUMINPUT: OK
	test VIDIOC_G/S_AUDIO: OK (Not Supported)
	Inputs: 1 Audio Inputs: 0 Tuners: 0

Output ioctls:
	test VIDIOC_G/S_MODULATOR: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_ENUMAUDOUT: OK (Not Supported)
	test VIDIOC_G/S/ENUMOUTPUT: OK (Not Supported)
	test VIDIOC_G/S_AUDOUT: OK (Not Supported)
	Outputs: 0 Audio Outputs: 0 Modulators: 0

Input/Output configuration ioctls:
	test VIDIOC_ENUM/G/S/QUERY_STD: OK (Not Supported)
	test VIDIOC_ENUM/G/S/QUERY_DV_TIMINGS: OK (Not Supported)
	test VIDIOC_DV_TIMINGS_CAP: OK (Not Supported)
	test VIDIOC_G/S_EDID: OK (Not Supported)

Test input 0:

	Control ioctls:
		test VIDIOC_QUERY_EXT_CTRL/QUERYMENU: OK
		test VIDIOC_QUERYCTRL: OK
		test VIDIOC_G/S_CTRL: OK
		test VIDIOC_G/S/TRY_EXT_CTRLS: OK
		test VIDIOC_(UN)SUBSCRIBE_EVENT/DQEVENT: OK
		test VIDIOC_G/S_JPEGCOMP: OK (Not Supported)
		Standard Controls: 9 Private Controls: 9

	Format ioctls:
		test VIDIOC_ENUM_FMT/FRAMESIZES/FRAMEINTERVALS: OK
		test VIDIOC_G/S_PARM: OK (Not Supported)
		test VIDIOC_G_FBUF: OK (Not Supported)
		test VIDIOC_G_FMT: OK
		fail: v4l2-test-formats.cpp(662): Video Capture is valid, but no TRY_FMT was implemented
		test VIDIOC_TRY_FMT: FAIL
		warn: v4l2-test-formats.cpp(933): S_FMT cannot handle an invalid pixelformat.
		warn: v4l2-test-formats.cpp(934): This may or may not be a problem. For more information see:
		warn: v4l2-test-formats.cpp(935): http://www.mail-archive.com/linux-media@vger.kernel.org/msg56550.html
		fail: v4l2-test-formats.cpp(947): S_FMT cannot handle an invalid format
		test VIDIOC_S_FMT: FAIL
		test VIDIOC_G_SLICED_VBI_CAP: OK (Not Supported)
		test Cropping: OK (Not Supported)
		test Composing: OK (Not Supported)
		fail: v4l2-test-formats.cpp(1406): doioctl(node, VIDIOC_S_FMT, &fmt)
		fail: v4l2-test-formats.cpp(1503): doioctl(node, VIDIOC_S_FMT, &fmt)
		test Scaling: FAIL

	Codec ioctls:
		test VIDIOC_(TRY_)ENCODER_CMD: OK (Not Supported)
		test VIDIOC_G_ENC_INDEX: OK (Not Supported)
		test VIDIOC_(TRY_)DECODER_CMD: OK (Not Supported)

	Buffer ioctls:
		test VIDIOC_REQBUFS/CREATE_BUFS/QUERYBUF: OK
		test VIDIOC_EXPBUF: OK

Test input 0:


Total: 42, Succeeded: 39, Failed: 3, Warnings: 3
```

**Comment by YoshuaNava** [comment]
I wish to add that when trying to run the yavta command you just posted, we get the following output:
```

Device /dev/video0 opened.
Device `vi-output-0, daxc02 6-0010' on `platform:vi:0' (driver 'tegra-video') is a video capture (without mplanes) device.
Unable to set format: Invalid argument (22).

```

**Comment by wilkinsw** [comment]
Interesting.  Are you using the TX1 devboard, or another platform?  I'll take a look.  I'm excited that you guys want to use the driver!

**Comment by wilkinsw** [comment]
Here's what my yavta output is.  

```bash
ubuntu@tegra-ubuntu:~$ yavta /dev/video0 -c1 -n1 -s1280x720 -fSRGGB12 -Fdata.raw
Device /dev/video0 opened.
Device `vi-output-0, daxc02 6-0010' on `platform:vi:0' (driver 'tegra-video') is a video capture (without mplanes) device.
Video format set: SRGGB12 (32314752) 1280x720 (stride 2560) field any buffer size 1843200
Video format: SRGGB12 (32314752) 1280x720 (stride 2560) field none buffer size 1843200
3 buffers requested.
length: 1843200 offset: 0 timestamp type/source: mono/EoF
Buffer 0/0 mapped at address 0x7fa0f70000.
length: 1843200 offset: 1843200 timestamp type/source: mono/EoF
Buffer 1/0 mapped at address 0x7fa0dae000.
length: 1843200 offset: 3686400 timestamp type/source: mono/EoF
Buffer 2/0 mapped at address 0x7fa0bec000.
0 (0) [E] none 0 1843200 B 307.030308 307.075708 1.231 fps ts mono/EoF
Captured 1 frames in 0.857980 seconds (1.165528 fps, 2148301.099085 B/s).
3 buffers released.
```

I had to jump through some hoops to get the format working with the Nvidia ISP.  Try putting the library from this [post](https://devtalk.nvidia.com/default/topic/993852/jetson-tx1/mt9m021-streaming/post/5115471/#5115471) here:  /usr/lib/aarch64-linux-gnu/tegra/libnvodm_imager.so

**Comment by wilkinsw** [comment]
Where did you get your yavta?  There's a version that doesn't work.  See this thread:
https://devtalk.nvidia.com/default/topic/923984/jetson-tx1/ov5693-through-v4l2-interface-not-working-in-23-2/post/4835246/#4835246

**Comment by yanjundream** [comment]
Hi Atrer. Happy to see this driver and I am working with the same camera and TX1 now. Hope I can use your driver. But I am a new-bee here. Could you explain a little about how to implement you driver with my TX1 board? I have tried copy three files into my TX1 boot folder and then my TX1 can not start any more. I do not know whether there are something else need to do after the last step in your explanation? Thank you and waiting for your answers.

**Comment by wilkinsw** [comment]
Hi @yanjundream, I'd appreciate if you'd either make a new issue at the top, or message me on the Nvidia forums (https://devtalk.nvidia.com/member/2150964/).  In the meantime make sure you check out the correct kernel version.  I believe 24.2 is the newest that works on the TX1.  The newer versions are for TX2.  Happy to walk you through it in an alternate thread!

**Comment by wilkinsw** [comment]
As for @aravindev  and @YoshuaNava I was talking with your colleague offline and it looks like the root of the issue was that there was no pull up resistor on reset for your implementation.  Do you have an update on how your project is going?  Once my group gets our hardware out I'll implement the GPIO based reset in the code.

**Comment by yanjundream** [comment]
Thank you for your fast reply@Atrer! My vision is R24(release), REVISION:2.1 . I will start a new thread now. Thanks!

**Comment by aravindev** [comment]
@Atrer I have not yet been able to get a capture out. But I have managed to get the software GPIO configured. So, right now my i2cdetect result is as foloows
`ubuntu@tegra-ubuntu:~$ sudo i2cdetect -y -r 6`

>  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- 0e -- 
10: UU -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

I am sure whether the UU for 0x10 can be a real problem.
From the dmesg logs I see that Aptina sensor is detected at 0x10.
But still I see that the v4l2-compliance fails.
`ubuntu@tegra-ubuntu:~$ v4l2-compliance -d /dev/v4l/by-path/platform-vi-video-index0`

> Driver Info:
	Driver name   : tegra-video
	Card type     : vi-output-0, daxc02 6-0010
	Bus info      : platform:vi:0
	Driver version: 3.10.96
	Capabilities  : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Compliance test for device /dev/v4l/by-path/platform-vi-video-index0 (not using libv4l2):
Required ioctls:
	test VIDIOC_QUERYCAP: OK
Allow for multiple opens:
	test second video open: OK
	test VIDIOC_QUERYCAP: OK
	test VIDIOC_G/S_PRIORITY: OK
Debug ioctls:
	test VIDIOC_DBG_G/S_REGISTER: OK (Not Supported)
	test VIDIOC_LOG_STATUS: OK (Not Supported)
Input ioctls:
	test VIDIOC_G/S_TUNER/ENUM_FREQ_BANDS: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_S_HW_FREQ_SEEK: OK (Not Supported)
	test VIDIOC_ENUMAUDIO: OK (Not Supported)
	test VIDIOC_G/S/ENUMINPUT: OK
	test VIDIOC_G/S_AUDIO: OK (Not Supported)
	Inputs: 1 Audio Inputs: 0 Tuners: 0
Output ioctls:
	test VIDIOC_G/S_MODULATOR: OK (Not Supported)
	test VIDIOC_G/S_FREQUENCY: OK (Not Supported)
	test VIDIOC_ENUMAUDOUT: OK (Not Supported)
	test VIDIOC_G/S/ENUMOUTPUT: OK (Not Supported)
	test VIDIOC_G/S_AUDOUT: OK (Not Supported)
	Outputs: 0 Audio Outputs: 0 Modulators: 0
Input/Output configuration ioctls:
	test VIDIOC_ENUM/G/S/QUERY_STD: OK (Not Supported)
	test VIDIOC_ENUM/G/S/QUERY_DV_TIMINGS: OK (Not Supported)
	test VIDIOC_DV_TIMINGS_CAP: OK (Not Supported)
	test VIDIOC_G/S_EDID: OK (Not Supported)
Test input 0:
	Control ioctls:
		test VIDIOC_QUERY_EXT_CTRL/QUERYMENU: OK
		test VIDIOC_QUERYCTRL: OK
		test VIDIOC_G/S_CTRL: OK
		test VIDIOC_G/S/TRY_EXT_CTRLS: OK
		test VIDIOC_(UN)SUBSCRIBE_EVENT/DQEVENT: OK
		test VIDIOC_G/S_JPEGCOMP: OK (Not Supported)
		Standard Controls: 9 Private Controls: 9
	Format ioctls:
		test VIDIOC_ENUM_FMT/FRAMESIZES/FRAMEINTERVALS: OK
		test VIDIOC_G/S_PARM: OK (Not Supported)
		test VIDIOC_G_FBUF: OK (Not Supported)
		test VIDIOC_G_FMT: OK
		fail: v4l2-test-formats.cpp(330): colorspace >= 0xff
		fail: v4l2-test-formats.cpp(432): testColorspace(pix.pixelformat, pix.colorspace, pix.ycbcr_enc, pix.quantization)
		fail: v4l2-test-formats.cpp(732): Video Capture is valid, but TRY_FMT failed to return a format
		test VIDIOC_TRY_FMT: FAIL
		fail: v4l2-test-formats.cpp(330): colorspace >= 0xff
		fail: v4l2-test-formats.cpp(432): testColorspace(pix.pixelformat, pix.colorspace, pix.ycbcr_enc, pix.quantization)
		fail: v4l2-test-formats.cpp(952): Video Capture is valid, but no S_FMT was implemented
		test VIDIOC_S_FMT: FAIL
		test VIDIOC_G_SLICED_VBI_CAP: OK (Not Supported)
		test Cropping: OK (Not Supported)
		test Composing: OK (Not Supported)
		fail: v4l2-test-formats.cpp(1486): node->can_scale && node->frmsizes_count[v4l_format_g_pixelformat(&cur)]
		test Scaling: OK
	Codec ioctls:
		test VIDIOC_(TRY_)ENCODER_CMD: OK (Not Supported)
		test VIDIOC_G_ENC_INDEX: OK (Not Supported)
		test VIDIOC_(TRY_)DECODER_CMD: OK (Not Supported)
	Buffer ioctls:
		test VIDIOC_REQBUFS/CREATE_BUFS/QUERYBUF: OK
		test VIDIOC_EXPBUF: OK
Test input 0:
Total: 42, Succeeded: 40, Failed: 2, Warnings: 0

As you can see, the S_FMT and TRY_FMT throws error.
I was wondering what could be wrong. Does your driver pass all these tests? In the nvidia forum, I remember reading a similar log from you, for which you later said that you fixed it, but I was wondering what the changes are.

Also, could the number of lanes configured be the culprit? I haven't tried playing with it yet.
Thanks
Aravind

**Comment by aravindev** [comment]
Snippet from the dmesg while running the compliance test:

> [  780.448294] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.448895] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.448912] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.448922] daxc02 6-0010: could not find device ctrl.
[  780.454312] daxc02 6-0010: could not find device ctrl.
[  780.459767] daxc02 6-0010: mt9m021_set_format
               	width: 16384
               	height: 32768
               	code: 12306
[  780.459890] daxc02 6-0010: could not find device ctrl.
[  780.465957] daxc02 6-0010: could not find device ctrl.
[  780.472836] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.472848] daxc02 6-0010: mt9m021_set_format
               	width: 16384
               	height: 32768
               	code: 12306
[  780.472855] daxc02 6-0010: could not find device ctrl.
[  780.478356] daxc02 6-0010: could not find device ctrl.
[  780.483594] daxc02 6-0010: mt9m021_set_format
               	width: 16384
               	height: 32768
               	code: 12306
[  780.483602] daxc02 6-0010: could not find device ctrl.
[  780.491110] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.491123] daxc02 6-0010: mt9m021_set_format
               	width: 16
               	height: 32
               	code: 12306
[  780.491129] daxc02 6-0010: could not find device ctrl.
[  780.496487] daxc02 6-0010: could not find device ctrl.
[  780.501918] daxc02 6-0010: mt9m021_set_format
               	width: 16
               	height: 32
               	code: 12306
[  780.501926] daxc02 6-0010: could not find device ctrl.
[  780.507071] daxc02 6-0010: mt9m021_set_format
               	width: 16384
               	height: 16384
               	code: 12306
[  780.507078] daxc02 6-0010: could not find device ctrl.
[  780.512240] daxc02 6-0010: could not find device ctrl.
[  780.517409] daxc02 6-0010: mt9m021_set_format
               	width: 16384
               	height: 16384
               	code: 12306
[  780.517415] daxc02 6-0010: could not find device ctrl.
[  780.523055] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.523062] daxc02 6-0010: could not find device ctrl.
[  780.528329] daxc02 6-0010: could not find device ctrl.
[  780.533521] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.533527] daxc02 6-0010: could not find device ctrl.
[  780.575877] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575897] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575918] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575927] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575960] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575977] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.575994] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.576002] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.576027] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.576043] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.576060] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.576070] daxc02 6-0010: mt9m021_get_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.588893] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.588903] daxc02 6-0010: could not find device ctrl.
[  780.594179] daxc02 6-0010: could not find device ctrl.
[  780.599345] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.599351] daxc02 6-0010: could not find device ctrl.
[  780.604512] daxc02 6-0010: daxc02_s_ctrl: V4L2_CID_TEST_PATTERN
[  780.604517] daxc02 6-0010: mt9m021_write: 0x0000 to 0x3070
[  780.604811] daxc02 6-0010: mt9m021_write: 0x0000 to 0x3070
[  780.605625] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.605632] daxc02 6-0010: could not find device ctrl.
[  780.610925] daxc02 6-0010: could not find device ctrl.
[  780.616060] daxc02 6-0010: mt9m021_set_format
               	width: 1280
               	height: 720
               	code: 12306
[  780.616066] daxc02 6-0010: could not find device ctrl.

**Comment by wilkinsw** [comment]
The "UU" on 0x10 just means their is a driver controlling the device at that address.  It's a good thing.

It doesn't pass the compliance test for the format selection, but that's never been an issue.

I have not been able to get the camera working with more than one MIPI lane, but that should be how it's set up in the DTSI already.  What does your hardware look like?  We almost have ours ready to go.

**Comment by aravindev** [comment]
It's a very similar configuration as yours, with a MIPI bridge IC communicating. I got some additional code in and get the following prints from the drivers/media/platform/tegra/csi/csi2_fops.c

Whenever I try streaming, I receive the following error in dmesg:
`[ 1793.043699] vi vi: vi2_channel_error_status:error 4000 frame 18`
So, after adding print's in the aforementioned file , this is what I see
>[ 1792.462499] csi2_pp_read:offset 0x0000001c
[ 1792.466664] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004014
[ 1792.466725] csi2_pp_write:offset 0x0000001c val:0x00004014
[ 1792.473144] csi2_cil_read:offset 0x00000010
[ 1792.477553] TEGRA_CSI_CIL_STATUS : 0x00000011
[ 1792.477614] csi2_cil_write:offset 0x00000010 val:0x00000011
[ 1792.483984] csi2_cil_read:offset 0x00000014
[ 1792.488215] TEGRA_CSI_CILX_STATUS : 0x00040010
[ 1792.488221] csi2_cil_write:offset 0x00000014 val:0x00040010
[ 1792.493853] vi vi: vi2_channel_error_status:error 4000 frame 3
[ 1792.501343] csi2_pp_read:offset 0x0000001c
[ 1792.505519] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.505524] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.511015] csi2_cil_read:offset 0x00000010
[ 1792.515241] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.515246] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.520821] csi2_cil_read:offset 0x00000014
[ 1792.525049] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.525053] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.530630] vi vi: vi2_channel_error_status:error 4000 frame 4
[ 1792.537777] csi2_pp_read:offset 0x0000001c
[ 1792.541912] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.541916] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.547403] csi2_cil_read:offset 0x00000010
[ 1792.551628] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.551632] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.557210] csi2_cil_read:offset 0x00000014
[ 1792.561520] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.561524] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.567099] vi vi: vi2_channel_error_status:error 4000 frame 5
[ 1792.574581] csi2_pp_read:offset 0x0000001c
[ 1792.578677] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.578680] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.584208] csi2_cil_read:offset 0x00000010
[ 1792.588399] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.588403] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.594012] csi2_cil_read:offset 0x00000014
[ 1792.598202] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.598205] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.603813] vi vi: vi2_channel_error_status:error 4000 frame 6
[ 1792.610897] csi2_pp_read:offset 0x0000001c
[ 1792.615036] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.615040] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.620529] csi2_cil_read:offset 0x00000010
[ 1792.624756] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.624760] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.630514] csi2_cil_read:offset 0x00000014
[ 1792.634787] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.634791] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.640380] vi vi: vi2_channel_error_status:error 4000 frame 7
[ 1792.647634] csi2_pp_read:offset 0x0000001c
[ 1792.651782] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.651786] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.657279] csi2_cil_read:offset 0x00000010
[ 1792.661518] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.661522] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.667191] csi2_cil_read:offset 0x00000014
[ 1792.671372] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.671375] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.677058] vi vi: vi2_channel_error_status:error 4000 frame 8
[ 1792.684571] csi2_pp_read:offset 0x0000001c
[ 1792.688667] TEGRA_CSI_PIXEL_PARSER_STATUS : 0x00004015
[ 1792.688670] csi2_pp_write:offset 0x0000001c val:0x00004015
[ 1792.694205] csi2_cil_read:offset 0x00000010
[ 1792.698400] TEGRA_CSI_CIL_STATUS : 0x00000001
[ 1792.698404] csi2_cil_write:offset 0x00000010 val:0x00000001
[ 1792.704019] csi2_cil_read:offset 0x00000014
[ 1792.708210] TEGRA_CSI_CILX_STATUS : 0x00000010
[ 1792.708213] csi2_cil_write:offset 0x00000014 val:0x00000010
[ 1792.713821] vi vi: vi2_channel_error_status:error 4000 frame 9

- Doyou have any suggestions? 
- What was the reason behind removing camera common? When I remove it, I observe a lot of kernel panic in the dmesg logs.
- Why did you use RG12 instead of BA12? 
- Also, is there any reference for the PLL configurations that you are using.
- I also found that the MT9M021_BINNING_DEF definition declared as 0x20 was supposed to be 0x22. Is that intentional?
- Do you know any way to check the CSI port is functioning or to check whether the bridge is up and running?

**Comment by aravindev** [comment]
When I enable streaming with your code, I observe this error. Do you have any idea what this can be caused by?
[  136.078719] vi vi: vi2_channel_error_status:error 4022 frame 0
[  136.111992] vi vi: vi2_channel_error_status:error 4022 frame 1
[  136.128580] vi vi: vi2_channel_error_status:error 4022 frame 2

**Comment by wilkinsw** [comment]
I tried to avoid using Camera Common as much as possible since it seemed very rigid in what you could do.  But I ended up using it quite a bit to make everything work with Nvidia's system.

As for BA12, Nvidia only supports RG12, so I set MT9M021_X_ADDR_START to 1 so it skips the first column and reads it in as RG12.

I used a configuration file from Leopard and an old Aptina driver as a reference, so I'm not sure where the MT9M021_BINNING_DEF came from.  You can change it if you want to, pretty sure I checked the datasheet at some point about that and it was fine.

We used an SN75DPHY440SS as a buffer chip after the TC358746AXBG MIPI converter.  CSI is notoriously difficult to test since it's such high speed and test points can damage the signal.

**Comment by wilkinsw** [comment]
I don't know what the actual error code is, but it's probably a timeout from not getting any image data.

**Comment by yanjundream** [comment]
Good to know you have used a buffer chip. Are there any code associate with the function of this buffer particularly? In my side, the MIPI lans are directly connected to TX1.

**Comment by wilkinsw** [comment]
Nope, the buffer chip doesn't require anything special.

**Comment by aravindev** [comment]
I managed to fix all the issues we were facing and got image captured using yavta and v4l2-ctl.
I am currently getting the same error as you were previously obtaining while trying to use gstreamer and nvgstcapture. But changing the framerate as mentioned in your solution, didn't help.
Can you share the commands that you use with your current driver? Is there anything to be changed in the system so that it works?

**Comment by wilkinsw** [comment]
Make sure you update, I've made some improvements.  To stream to VLC I do something like this command:



## VLC RTP Streaming

IP={YOUR_IP_HERE}
PORT=5000

gst-launch-1.0 -v nvcamerasrc contrast=1 intent=3 auto-exposure=2 sensor_id=0 fpsRange="15 15" intent=3 ! 'video/x-raw(memory:NVMM), width=(int)320, height=(int)180, format=(string)I420, framerate=(fraction)15/1' ! omxh264enc control-rate=2 bitrate=2000000 ! 'video/x-h264, stream-format=(string)byte-stream' ! h264parse ! mpegtsmux ! rtpmp2tpay ! udpsink host=${IP} port=${PORT} sync=false async=false

On my windows computer I open VLC and go to Media -> Open Network Stream... -> rtp://0.0.0.0:5000

**Comment by wilkinsw** [comment]
Closing this due to there being no updates in a month.
