### ISSUE TITLE
extend documentation regarding tx2 support and carrier board

### ISSUE THREAD

**Issue by rifotu** [DaxBot/daxc02#5]
Hello,

Can you please update wiki regarding the carrier board ( DAX-C02 ) timeline?
Also can we use this driver with Jetson Tx2?

**Comment by wilkinsw** [comment]
Checking with TX2 is on my lists.  There's no real ETA at this time.  There are other projects in the queue that take priority.

**Comment by rifotu** [comment]
Hello,
Thanks for the answer. Is it then possible to share the schematics so that we can do our board and use it in our projects?

**Comment by wilkinsw** [comment]
Talked to my team, we will probably have the changes made and a few boards available in mid September.  I'll let everyone know when they get ordered.

**Comment by deksprime** [comment]
What is the name of your company? I too would like to see the boards' schematics to see if we can use them for our robots.

**Comment by wilkinsw** [comment]
We're going to be releasing the schematic and information on the hardware soon.  Note that all of this is a work in progress and not guaranteed to be perfect.

We can sell you a finished board for $500, hand soldered and tested by our electrical engineer, but we'd encourage using the schematic to build your own.

**Comment by wilkinsw** [comment]
@deksprime @rifotu 
We have extra boards and the licensing is all figured out if either of you are still interested in hardware.

I spent some time trying to update the driver to the TX2 and wasn't successful, so right now it's only validated for Jetson r24.2.  It's on my list to get back to eventually though.

**Comment by wilkinsw** [comment]
README is updated for installation on the TX2, and the driver probes.  Just need to figure out why it's not giving an image.
